spring:
  profiles:
    active: dev
  application:
    name: pokedex-api
  datasource:
    url: jdbc:postgresql://localhost:5432/pokedex_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
  data:
    mongodb:
      uri: mongodb://localhost:27017/pokedex_stats

server:
  port: 8080
  servlet:
    context-path: /api

app:
  jwt:
    secret: ${JWT_SECRET:claveDePruebaParaDesarrolloCambiarLuego1234567890}
    expiration-ms: 86400000